### ISSUE TITLE
Possible issue : Exception in thread "main" java.lang.IllegalStateException: Unexpected value of type 'com.skynav.ttv.model.ttml2.ttd.TimeBase

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttt#148] opened 2015-09-15 16:10 UTC
When the following command line was used for ttpe:

rpuri@lgld-rpuri:~/Projects/ttt$ java -cp ttt-jars/*: com.skynav.ttpe.app.Presenter --model ttml2 -v --debug-exceptions --output-indent --default-color white --external-duration 24h --external-frame-rate 29.970 --external-extent '1280px 720px' --png-generation-mode region --font-directory /home/rpuri/Projects/ttt/ttt-ttpe/src/test/fonts/ --output-directory /home/rpuri/Projects/ttt/work --output-retain-manifest --output-retain-frames --output-format png --png-background transparent --output-pattern-isd 'isdi{0,number,000000}.xml' --output-retain-isd /media/HD_NTFS/data/captions/arabic_ttml_samples/small.xml.gsdh.xml

the following stack trace was observed:

rpuri@lgld-rpuri:~/Projects/ttt$ java -cp ttt-jars/*: com.skynav.ttpe.app.Presenter --model ttml2 -v --debug-exceptions --output-indent --default-color white --external-duration 24h --external-frame-rate 29.970 --external-extent '1280px 720px' --png-generation-mode region --font-directory /home/rpuri/Projects/ttt/ttt-ttpe/src/test/fonts/ --output-directory /home/rpuri/Projects/ttt/work --output-retain-manifest --output-retain-frames --output-format png --png-background transparent --output-pattern-isd 'isdi{0,number,000000}.xml' --output-retain-isd /media/HD_NTFS/data/captions/arabic_ttml_samples/small.xml.gsdh.xml
Timed Text Presentation Engine (TTPE) [1.0.0dev] Copyright 2013-15 Skynav, Inc.
Exception in thread "main" java.lang.IllegalStateException: Unexpected value of type 'com.skynav.ttv.model.ttml2.ttd.TimeBase
	at com.skynav.ttv.verifier.ttml.parameter.TimeBaseVerifier.verify(TimeBaseVerifier.java:44)
	at com.skynav.ttv.verifier.ttml.TTML1ParameterVerifier$ParameterAccessor.verify(TTML1ParameterVerifier.java:351)
	at com.skynav.ttv.verifier.ttml.TTML1ParameterVerifier.verifyAttributeItems(TTML1ParameterVerifier.java:219)
	at com.skynav.ttv.verifier.ttml.TTML1ParameterVerifier.verify(TTML1ParameterVerifier.java:209)
	at com.skynav.ttv.verifier.ttml.TTML1SemanticsVerifier.verifyTimedTextParameterAttributes(TTML1SemanticsVerifier.java:769)
	at com.skynav.ttv.verifier.ttml.TTML1SemanticsVerifier.verifyTimedText(TTML1SemanticsVerifier.java:144)
	at com.skynav.ttv.verifier.ttml.TTML2SemanticsVerifier.verifyRoot(TTML2SemanticsVerifier.java:72)
	at com.skynav.ttv.verifier.ttml.TTML1SemanticsVerifier.verify(TTML1SemanticsVerifier.java:99)
	at com.skynav.ttv.app.TimedTextVerifier.verifySemantics(TimedTextVerifier.java:1943)
	at com.skynav.ttv.app.TimedTextVerifier.verify(TimedTextVerifier.java:1977)
	at com.skynav.ttv.app.TimedTextVerifier.verify(TimedTextVerifier.java:2101)
	at com.skynav.ttv.app.TimedTextVerifier.run(TimedTextVerifier.java:2168)
	at com.skynav.ttx.app.TimedTextTransformer.run(TimedTextTransformer.java:444)
	at com.skynav.ttx.app.TimedTextTransformer.run(TimedTextTransformer.java:440)
	at com.skynav.ttpe.app.Presenter.main(Presenter.java:201)

I am pasting the source file as below:
++++++++++++++++++++++++++++++++++++++
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tt xmlns:nttm="http://www.netflix.com/ns/ttml#metadata" xmlns:tt="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" ttp:frameRate="24" ttp:frameRateMultiplier="1000 1001" ttp:timeBase="media" ttp:version="2" xml:lang="ar" xml:space="default" xmlns="http://www.w3.org/ns/ttml">
    <head>
        <metadata nttm:movieID="-1" nttm:packageID="-1" nttm:schemaVersion="0" nttm:textType="SUBS" nttm:uuid="ec6d77ca-80e2-4a49-8d1b-14be6dabf08b"/>
        <styling>
            <initial tts:extent="auto" tts:fontSize="6.0vh" tts:lineHeight="7.5vh" tts:origin="auto" tts:showBackground="whenActive"/>
            <style tts:color="white" tts:displayAlign="after" tts:fontSize="100.0%" tts:fontWeight="normal" tts:textAlign="center" xml:id="css0"/>
            <style tts:color="white" tts:direction="rtl" tts:fontSize="100.0%" tts:fontWeight="normal" tts:textAlign="center" tts:unicodeBidi="bidiOverride" xml:id="css1"/>
        </styling>
    </head>
    <body>
        <div>
            <p begin="00:01:57.317" end="00:02:04.290" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">إمبريسز إن دي بالاس</span>
            </p>
            <p begin="00:02:04.924" end="00:02:10.463" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">الحلقة الثانية</span>
            </p>
            <p begin="00:02:15.268" end="00:02:18.638" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">هذا هو المكان حيث تم دفع ماي</span>
                <br/>
                <span style="css1">وسقطت في الماء</span>
            </p>
            <p begin="00:02:19.873" end="00:02:23.476" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">حسبت أنه في حال ظللت أكسب فضل جلالته</span>
            </p>
            <p begin="00:02:23.543" end="00:02:25.612" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">وكنت محاطة بأصدقاء حقيقيين</span>
            </p>
            <p begin="00:02:25.678" end="00:02:30.783" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">لكنت استطعت عيش حياة إمبراطورية</span>
                <br/>
                <span style="css1">بصفتي لايدي وان بلا أي هموم</span>
            </p>
            <p begin="00:02:31.818" end="00:02:34.854" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">كنت مخطئة وساذجة إلى أقصى حد</span>
            </p>
            <p begin="00:02:35.221" end="00:02:39.425" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">بالكاد أدركت أن الدولة والحريم تديرها</span>
                <br/>
                <span style="css1">القوى نفسها</span>
            </p>
            <p begin="00:02:39.492" end="00:02:45.465" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">إنه عالم قاس مليء بالسباقات الدامية</span>
            </p>
            <p begin="00:02:45.532" end="00:02:49.602" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">تنافست العشيقات في الحريم من أجل جلالته</span>
                <br/>
                <span style="css1">بالطرق كلها</span>
            </p>
            <p begin="00:02:49.669" end="00:02:52.839" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">أوقعت الأخريات ماي في الفخ</span>
                <br/>
                <span style="css1">وأوشكت على مفارقة الحياة</span>
            </p>
            <p begin="00:02:52.906" end="00:02:56.776" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">كانت مخاطرة. بالكاد نجوت من مخالب</span>
                <br/>
                <span style="css1">الخطر مرات عدة</span>
            </p>
            <p begin="00:02:57.911" end="00:03:01.614" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">كان من المستحيل ألا أتورط في جدال معين</span>
            </p>
            <p begin="00:03:01.681" end="00:03:05.885" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">وعلى حين غفلة كنت أنجر في نزاع</span>
            </p>
            <p begin="00:03:09.455" end="00:03:12.792" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">تعطينا إدارة شؤون الأسرة الإمبراطورية</span>
                <br/>
                <span style="css1">أرفع السلع</span>
            </p>
            <p begin="00:03:12.859" end="00:03:15.862" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">تسمح أيضاً للطبيب وين بإرسال</span>
                <br/>
                <span style="css1">مشروبه الطبي كل يوم</span>
            </p>
            <p begin="00:03:15.929" end="00:03:18.731" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">أتعتقدين أن ذلك جيد؟</span>
                <br/>
                <span style="css1">كان مذاق الدواء مراً جداً</span>
            </p>
            <p begin="00:03:21.234" end="00:03:24.470" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">ثمة مسألة أخرى لقد تمادت يو كثيراً</span>
            </p>
            <p begin="00:03:24.537" end="00:03:27.840" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">يقولون إنها تلعنك باستمرار</span>
                <br/>
                <span style="css1">منذ الانتقال من قصر تشونتشوي</span>
            </p>
            <p begin="00:03:28.942" end="00:03:30.610" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">دعيها وشأنها</span>
            </p>
            <p begin="00:03:30.677" end="00:03:32.412" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">ضميري مرتاح</span>
            </p>
            <p begin="00:03:32.946" end="00:03:34.614" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">سنغفر لها عندما يحين الوقت المناسب</span>
            </p>
            <p begin="00:03:34.681" end="00:03:36.516" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">لقد خسرت الكثير وغضبها طبيعي</span>
            </p>
            <p begin="00:03:37.016" end="00:03:38.851" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">ستهدأ مع الوقت</span>
            </p>
            <p begin="00:03:39.586" end="00:03:41.588" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">أنت غاية في اللطف أيتها الخليلة الشابة</span>
            </p>
            <p begin="00:03:42.922" end="00:03:44.824" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">دواؤك جاهز أيتها الخليلة</span>
            </p>
            <p begin="00:03:52.832" end="00:03:54.634" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">مذاق الدواء مر مؤخراً</span>
            </p>
            <p begin="00:03:55.535" end="00:03:57.770" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">ربما هو وصفة طبية جديدة من الطبيب وين</span>
            </p>
            <p begin="00:04:01.708" end="00:04:04.677" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">نهضت منذ وقت قصير،</span>
                <br/>
                <span style="css1">وها أنا أشعر بالتعب من جديد</span>
            </p>
            <p begin="00:04:05.345" end="00:04:08.948" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">كنت دوما تشعرين بالنعاس مؤخراً</span>
                <br/>
                <span style="css1">بعد وقت قليل من نهوضك</span>
            </p>
            <p begin="00:04:10.316" end="00:04:11.818" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">ساعديني في الداخل لأنام قليلاً</span>
            </p>
            <p begin="00:04:17.690" end="00:04:18.691" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">هوانبي</span>
            </p>
            <p begin="00:04:20.059" end="00:04:21.961" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">متى أصبحت خاملة إلى هذه الدرجة؟</span>
            </p>
            <p begin="00:04:23.463" end="00:04:25.865" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">كنت تشعرين بالتعب باستمرار لـ 3 أو 5 أيام</span>
            </p>
            <p begin="00:04:25.932" end="00:04:28.901" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">كنت نائمة خلال 10 إلى 12 ساعة</span>
                <br/>
                <span style="css1">من أصل 24 ساعة في اليوم</span>
            </p>
            <p begin="00:04:28.968" end="00:04:32.272" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">زارك جلالته قبل يومين في وقت متأخر</span>
                <br/>
                <span style="css1">من الصباح</span>
            </p>
            <p begin="00:04:32.772" end="00:04:34.607" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">وكنت لا تزالين نائمة في السرير</span>
            </p>
            <p begin="00:04:35.708" end="00:04:37.644" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">أتعشرين أيضاً وجود خطب ما؟</span>
            </p>
            <p begin="00:04:37.710" end="00:04:40.613" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">أرجوك إبقي مستيقظة أيتها الخليلة الشابة</span>
                <br/>
                <span style="css1">سأطلب حضور الطبيب وين</span>
            </p>
            <p begin="00:04:42.415" end="00:04:44.584" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">تعرف نقطة الوخز بالإبر بنقطة هيغو</span>
            </p>
            <p begin="00:04:44.651" end="00:04:46.819" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">إن كان نعاسك عارضاً طبيعياً،</span>
            </p>
            <p begin="00:04:47.487" end="00:04:49.422" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">سيساعدك الوخز بالإبر في هذه الحالة</span>
            </p>
            <p begin="00:04:49.489" end="00:04:52.525" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">إن كان السبب مخدراً قد يتغير لون الإبرة</span>
            </p>
            <p begin="00:04:58.531" end="00:05:01.100" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">كما توقعت، قام أحدهم بالتلاعب بدوائي</span>
            </p>
            <p begin="00:05:03.636" end="00:05:07.540" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">أرجوك أنظري أيتها الخليلة الشابة</span>
                <br/>
                <span style="css1">تحول طرف الإبرة إلى أخضر فاتح</span>
            </p>
            <p begin="00:05:08.541" end="00:05:10.710" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">ما هذا؟ سم؟</span>
            </p>
            <p begin="00:05:10.777" end="00:05:12.045" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">كلا، ليس كذلك</span>
            </p>
            <p begin="00:05:12.745" end="00:05:16.382" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">بدل أحدهم جرعة وصفتي</span>
            </p>
            <p begin="00:05:16.449" end="00:05:19.452" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">تم القيام بذلك بدقة عبر إضافة</span>
                <br/>
                <span style="css1">كمية قليلة جداً</span>
            </p>
            <p begin="00:05:19.519" end="00:05:22.955" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">رغم أنني أطمئن عليك يومياً</span>
                <br/>
                <span style="css1">من الصعب أن نستطلع ذلك</span>
            </p>
            <p begin="00:05:23.723" end="00:05:27.994" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">ولكن إن تناولت هذا الدواء على فترة طويلة</span>
            </p>
            <p begin="00:05:28.061" end="00:05:31.631" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">ستشعرين بالإرهاق والنعاس في البداية</span>
            </p>
            <p begin="00:05:31.698" end="00:05:35.435" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">وستصابين بالجنون في غضون 6 أشهر</span>
                <br/>
                <span style="css1">وسينتهي بك الأمر بالهذيان التام</span>
            </p>
            <p begin="00:05:35.935" end="00:05:38.571" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">لا بد أن الآثم يفكر جيداً بي</span>
            </p>
            <p begin="00:05:38.638" end="00:05:41.340" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">ليحاول أن يزيلني عن الوجود</span>
                <br/>
                <span style="css1">بهذه الطريقة الحاذقة</span>
            </p>
            <p begin="00:05:41.407" end="00:05:43.443" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">لحسن الحظ أننا اكتشفنا الموضوع</span>
            </p>
            <p begin="00:05:43.509" end="00:05:46.546" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">ستتماثلين للشفاء عبر العلاج</span>
                <br/>
                <span style="css1">أيتها الخليلة الشابة</span>
            </p>
            <p begin="00:05:47.346" end="00:05:50.650" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">يتم توزيع الأدوية كلها بوصفتك</span>
                <br/>
                <span style="css1">ويتم تحضيرها في قصري</span>
            </p>
            <p begin="00:05:50.717" end="00:05:56.122" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">يبدو أن الجاريات والخدام المخصيين على</span>
                <br/>
                <span style="css1">رأس لائحة المشتبه بهم. يجب أن نتوخى الحذر</span>
            </p>
            <p begin="00:05:56.789" end="00:05:58.958" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">ما خطتك أيتها الخليلة؟</span>
            </p>
            <p begin="00:06:02.829" end="00:06:06.032" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">قمت بتحقيقات. كانت هواسوي قبلاً</span>
                <br/>
                <span style="css1">خادمة المسؤولة يو</span>
            </p>
            <p begin="00:06:06.099" end="00:06:09.168" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">تم إرسال العديد من خدامها بعد تنزيلها</span>
                <br/>
                <span style="css1">من رتبتها</span>
            </p>
            <p begin="00:06:09.402" end="00:06:12.371" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">كانت هواسوي من بينهم</span>
                <br/>
                <span style="css1">وتم تعيينها لاحقاً كخادمة لك</span>
            </p>
            <p begin="00:06:13.172" end="00:06:15.775" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">أنا متأكدة من أن تلك الخادمة</span>
                <br/>
                <span style="css1">خططت لتنتقم لـ يو</span>
            </p>
            <p begin="00:06:17.176" end="00:06:19.812" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">يا لهذا الوفاء</span>
            </p>
            <p begin="00:06:19.879" end="00:06:22.682" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">أرجوك أن تعفي عني!</span>
            </p>
            <p begin="00:06:23.883" end="00:06:25.718" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">قولي الحقيقة</span>
            </p>
            <p begin="00:06:25.785" end="00:06:27.920" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">إن تجرأت وكذبت أو أخفيت الحقيقة</span>
            </p>
            <p begin="00:06:27.987" end="00:06:30.189" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">سيتم جرك خارجاً وضربك حتى الموت</span>
            </p>
            <p begin="00:06:30.423" end="00:06:33.059" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">بعد أن أصبحت خادمتك</span>
            </p>
            <p begin="00:06:33.126" end="00:06:36.162" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">استدعتني يو إلى منزلها في يوم من الأيام</span>
            </p>
            <p begin="00:06:36.395" end="00:06:38.464" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">كافأتني بمبلغ كبير جداً</span>
            </p>
            <p begin="00:06:38.965" end="00:06:43.069" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">قالت الآنسة يو إنني لن أقلق حيال أي شيء</span>
            </p>
            <p begin="00:06:43.136" end="00:06:47.006" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">كانت مهمتي الوحيدة تقضي بوضع شيء</span>
                <br/>
                <span style="css1">في دوائك ووجباتك</span>
            </p>
            <p begin="00:06:47.607" end="00:06:51.477" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">حفرت حفرة في زاوية الحائط بناء</span>
                <br/>
                <span style="css1">على تعليماتها</span>
            </p>
            <p begin="00:06:51.544" end="00:06:54.781" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">عندما تريد الآنسة يو أن توصل</span>
                <br/>
                <span style="css1">رسالة أو مخدراً</span>
            </p>
            <p begin="00:06:55.548" end="00:06:59.919" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">يضع أحدهم ملاحظة في تلك الحفرة</span>
                <br/>
                <span style="css1">وأذهب لأخذها</span>
            </p>
            <p begin="00:06:59.986" end="00:07:01.721" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">متى وضعت الملاحظة هناك؟</span>
            </p>
            <p begin="00:07:02.622" end="00:07:07.160" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">جعلت السيدة يو أحدهم يضع</span>
                <br/>
                <span style="css1">المخدر في تلك الحفرة كل يومين</span>
            </p>
            <p begin="00:07:07.226" end="00:07:09.529" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">وعلي أن أذهب وآخذه</span>
            </p>
            <p begin="00:07:09.595" end="00:07:11.130" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">كل يومين</span>
            </p>
            <p begin="00:07:11.898" end="00:07:13.733" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">الموعد الليلة إذاً</span>
            </p>
            <p begin="00:07:14.534" end="00:07:17.437" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">متى تحصلين على المخدر؟ هل من كلمة سر؟</span>
            </p>
            <p begin="00:07:17.503" end="00:07:22.942" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">بين الساعتين الـ 7 والـ 9،</span>
                <br/>
                <span style="css1">نسمع إشارات تغريدات طيور من الخارج</span>
            </p>
            <p begin="00:07:23.009" end="00:07:25.178" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">ويتوجب علي أن أقوم بالإشارات</span>
                <br/>
                <span style="css1">نفسها رداً عليها</span>
            </p>
            <p begin="00:07:26.579" end="00:07:28.080" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">زاو يونزي</span>
            </p>
            <p begin="00:07:28.748" end="00:07:32.151" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">اربطوها في المخزن. لا تسمحوا لها بالإنتحار</span>
            </p>
            <p begin="00:07:32.218" end="00:07:33.619" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">حاضر أيتها الخليلة</span>
            </p>
            <p begin="00:07:33.686" end="00:07:34.887" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">هيا بنا</span>
            </p>
            <p begin="00:07:39.158" end="00:07:42.995" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">يجب أن أخبر ماي بشأن ما حصل</span>
            </p>
            <p begin="00:07:43.062" end="00:07:45.598" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">نعم، يجب أن نعلم لايدي شين</span>
            </p>
            <p begin="00:07:45.665" end="00:07:47.767" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">لتتمكنا معاً من صياغة الرد</span>
            </p>
            <p begin="00:07:47.834" end="00:07:50.603" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">- والمرافقة الثانية آن؟</span>
                <br/>
                <span style="css1">- لينغرونغ خجولة</span>
            </p>
            <p begin="00:07:50.970" end="00:07:53.206" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">لن نخبرها ستشعر بالرعب</span>
            </p>
            <p begin="00:08:15.895" end="00:08:17.663" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">بو-كو</span>
            </p>
            <p begin="00:08:20.233" end="00:08:21.067" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">بو-كو</span>
            </p>
            <p begin="00:08:22.201" end="00:08:23.035" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">بو-كو</span>
            </p>
            <p begin="00:08:26.572" end="00:08:29.809" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">أمسكوا به زاو يونزي، إنه هنا</span>
                <br/>
                <span style="css1">أسرعوا أخرجوا الآن</span>
            </p>
            <p begin="00:08:29.876" end="00:08:31.878" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">هيا، فلنلق القبض عليه</span>
            </p>
            <p begin="00:08:36.582" end="00:08:38.918" style="css0" tts:extent="80.0% 40.0%" tts:origin="10.0% 50.0%">
                <span style="css1">- دعوني أذهب</span>
                <br/>
                <span style="css1">- لا تقاوم!</span>
            </p>
        </div>
    </body>
</tt>

++++++++++++++++++++++++++++++++++++++++++

**Comment by skynavga** [comment] 2015-09-15 16:16
We believe this is a duplicate of #139, fixed in 2e180d0e41108c44f60c3bdfd74ee1e77242dbd8. Please ensure you are using ToT and update TTV jar as needed.

**Closed by skynavga** 2015-09-15 16:16 UTC
Labels: duplicate

**Comment by shimada-development** [comment] 2015-09-15 16:26
Hi Glenn,

i followed the following sequence of steps to update my local workspace.

git pull
 mvn -f ttt-deps/pom.xml install
mvn clean install
 java -cp ttt-jars/*: com.skynav.ttpe.app.Presenter --model ttml2 -v
--debug-exceptions --output-indent --default-color white
--external-duration 24h --external-frame-rate 29.970 --external-extent
'1280px 720px' --png-generation-mode region --font-directory
/home/rpuri/Projects/ttt/ttt-ttpe/src/test/fonts/ --output-directory
/home/rpuri/Projects/ttt/work --output-retain-manifest
--output-retain-frames --output-format png --png-background transparent
--output-pattern-isd 'isdi{0,number,000000}.xml' --output-retain-isd
/media/HD_NTFS/data/captions/arabic_ttml_samples/small.xml.gsdh.xml

I am still seeing this problem. The version of ttv that i have goes as:

rpuri@lgld-rpuri:~/Projects/ttt$ find . -name "*.jar" | grep ttv | xargs ls
-l
-rw-rw-r-- 1 rpuri rpuri 721133 Sep 15 09:18
./ttt-ttv/target/ttt-ttv-2.0-SNAPSHOT.jar

Am i missing out on some required step?

Thanks,
Rohit



On Tue, Sep 15, 2015 at 9:16 AM, Glenn Adams <notifications@github.com>
wrote:

> Closed #148 <https://github.com/skynav/ttt/issues/148>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skynav/ttt/issues/148#event-409982203>.
>
> --
> You received this message because you are subscribed to the Google Groups
> "Shimada Development" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to shimada-development+unsubscribe@netflix.com.
> To post to this group, send email to shimada-development@netflix.com.
> To view this discussion on the web visit
> https://groups.google.com/a/netflix.com/d/msgid/shimada-development/skynav/ttt/issue/148/issue_event/409982203%40github.com
> <https://groups.google.com/a/netflix.com/d/msgid/shimada-development/skynav/ttt/issue/148/issue_event/409982203%40github.com?utm_medium=email&utm_source=footer>
> .
>



-- 



Best regards,
Rohit Puri
(rpuri@netflix.com)

**Comment by shimada-development** [comment] 2015-09-15 16:33
did you copy the newly built ttv.jar into your ttt-jars directory that you
have configured your command line to use?

java -cp ttt-jars/*:
