### ISSUE TITLE
IMSC 1.1 contentProfiles

### ISSUE THREAD

**Issue by MsLizzie** [skynav/ttt#271] opened 2019-12-12 11:25 UTC
Hi,
It seems that it is not possible to validate any (actually valid) IMSC 1.1 file without at least 1 error.
According to the IMSC 1.1 spec:
https://www.w3.org/TR/ttml-imsc1.1/#general-1
**ttp:contentProfiles SHOULD be present on the tt element**

However, using ttp:contentProfiles always seems to result in a TTV error:

E.g.
*Timed Text Verifier (TTV) [7.1-SNAPSHOT] Copyright (c) 2013-19 Skynav, Inc.
[E]:{file:/Users/elizabeth.stone/Downloads/imsc1_1_test.xml}:[10,139]:Invalid {http://www.w3.org/ns/ttml#parameter}contentProfiles value 'http://www.w3.org/ns/ttml/profile/imsc1.1/text'.*

Also, if you remove the tt:contentProfiles attribute, then TTV only produces a warning. I believe that that situation should actually be an error, because ttp:contentProfiles SHOULD be present in IMSC 1.1

I've attached my simple example IMSC 1.1 file, which I believe should actually validate without any errors/warnings (I added a .txt extension, as it appears you can't upload xml directly
[imsc1_1_test.xml.txt](https://github.com/skynav/ttt/files/3955463/imsc1_1_test.xml.txt)
)

Thanks
Liz

**Comment by skynavga** [comment] 2019-12-12 12:29
Hi Liz,

Your problem is that you were asking TTV to validate the document as a TTML2 document rather than an IMSC11 (by using ``ttva:model="ttml2"``). If you change this to ``ttva:model="imsc11`` it should work just fine.

BTW, we already have an issue (#219) open to make ttml2 validation more flexible when it encounters profile designators from the profile registry that aren't strictly one of the ttml2 profiles.

I'm marking this issue as invalid and closing it on the presumption that you want to validate is as imsc11; however, if you really want to validate as ttml2 to, then it falls under the case of #219, in which case it is a duplicate of that issue, and I can relabel it as such (let me know which).

Glenn

**Closed** 2019-12-12 12:29 UTC
Labels: invalid, ttv

**Comment by MsLizzie** [comment] 2019-12-12 13:01
Hi Glenn
No, that's perfect. I did want to validate as imsc11, so changing to ttva:model="imsc11" is perfect.
Thank you for your quick response.

Liz
